name: flutter-dart-sync
description: Automatically updates the Dart SDK version in your pubspec.yaml to match the Dart version bundled with the installed Flutter SDK.
author: IamPekka058 <59747867+IamPekka058@users.noreply.github.com>

branding:
  icon: map-pin
  color: green

inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: '1000'

outputs:
  time:
    description: Your output description here

runs:
  using: node24
  main: dist/index.js
